version: '3.7'

services:

  backend:
    container_name: 'sentiment_backend'
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    ports:
      - 5001:5000
    environment:
      HUGGINGFACE_API_URL: ${HUGGINGFACE_API_URL}
      HUGGINGFACE_API_KEY: ${HUGGINGFACE_API_KEY}
      LLM_API: ${LLM_API}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      FLASK_ENV: "development"
      APP_SETTINGS: "app.config.DevelopmentConfig"
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/users_dev"
      DATABASE_TEST_URL: "postgresql://postgres:postgres@db:5432/users_test"
      SECRET_KEY: "ubu_secret_sentiment"
    depends_on:
      - db
    networks:
      - api_bridge
    restart: always

  db:
    container_name: 'sentiment_database'
    image: postgres:10.3
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - users_data:/var/lib/postgresql/data/
    networks:
      - api_bridge

  frontend:
    container_name: 'sentiment_frontend'
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3007:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - BACKEND_SERVICE_URL=http://backend:5000
      - VUE_GATEWAY_URL=http://frontend:8080
      - VUE_APP_API_URL=/api
    networks:
      - api_bridge

  nginx:
    container_name: 'sentiment_nginx'
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 443:443
    volumes:
      - /root/nginx/letsencrypt:/etc/nginx/conf.d/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - api_bridge

networks:
  api_bridge:
    driver: bridge

volumes:
  users_data:
  huggingface:
